{
 "title": "ALB TargetGroups",
 "description": "Shows AWS Application load balancer metrics from Cloudwatch",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "loadbalancer",
    "label": "Load Balancer",
    "query": "dimension_values($region, AWS/ApplicationELB, ActiveConnectionCount, LoadBalancer)"
   },
   {
    "name": "TargetGroup",
    "label": "TargetGroup",
    "query": "dimension_values($region,AWS/ApplicationELB,HealthyHostCount,TargetGroup, {\"LoadBalancer\":\"$loadbalancer\"})"
   }
  ]
 },
 "panels": [
  {
   "title": "Healthy targets",
   "type": "stat",
   "description": "The number of targets that are considered healthy.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$loadbalancer", "TargetGroup": "$TargetGroup" },
     "metricName": "HealthyHostCount",
     "namespace": "AWS/ApplicationELB",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "UnHealthy targets",
   "type": "stat",
   "description": "The number of targets that are considered unhealthy.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$loadbalancer", "TargetGroup": "$TargetGroup" },
     "metricName": "UnHealthyHostCount",
     "namespace": "AWS/ApplicationELB",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Consumed LCUs",
   "type": "stat",
   "description": "The number of load balancer capacity units (LCU) used by your load balancer.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "metricName": "ConsumedLCUs",
     "namespace": "AWS/ApplicationELB",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Target HTTP Response",
   "type": "graph",
   "description": "HTTP response code returned from the targets",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "HTTP 2XX",
     "dimensions": { "LoadBalancer": "$loadbalancer", "TargetGroup": "$TargetGroup" },
     "metricName": "HTTPCode_Target_2XX_Count",
     "namespace": "AWS/ApplicationELB",
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "HTTP 3XX",
     "dimensions": { "LoadBalancer": "$loadbalancer", "TargetGroup": "$TargetGroup" },
     "metricName": "HTTPCode_Target_3XX_Count",
     "namespace": "AWS/ApplicationELB",
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "HTTP 4XX",
     "dimensions": { "LoadBalancer": "$loadbalancer", "TargetGroup": "$TargetGroup" },
     "metricName": "HTTPCode_Target_4XX_Count",
     "namespace": "AWS/ApplicationELB",
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "HTTP 5XX",
     "dimensions": { "LoadBalancer": "$loadbalancer", "TargetGroup": "$TargetGroup" },
     "metricName": "HTTPCode_Target_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "RequestCount",
   "type": "graph",
   "description": "ELB Request metrics",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "RequestCountTotal",
     "dimensions": { "LoadBalancer": "$loadbalancer", "TargetGroup": "$TargetGroup" },
     "metricName": "RequestCountPerTarget",
     "namespace": "AWS/ApplicationELB",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Target Response Time",
   "type": "graph",
   "description": "The time elapsed, in seconds, after the request leaves the load balancer until a response from the target is received",
   "gridPos": { "h": 9, "w": 9, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "Response",
     "dimensions": { "LoadBalancer": "$loadbalancer", "TargetGroup": "$TargetGroup" },
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Host Count",
   "type": "graph",
   "description": "Target group host count",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Healthy Hosts",
     "dimensions": { "LoadBalancer": "$loadbalancer", "TargetGroup": "$TargetGroup" },
     "id": "a1",
     "metricName": "HealthyHostCount",
     "namespace": "AWS/ApplicationELB",
     "region": "$region",
     "statistics": [ "Maximum" ]
    },
    {
     "alias": "Unealthy Hosts",
     "dimensions": { "LoadBalancer": "$loadbalancer", "TargetGroup": "$TargetGroup" },
     "id": "a2",
     "metricName": "UnHealthyHostCount",
     "namespace": "AWS/ApplicationELB",
     "region": "$region",
     "statistics": [ "Maximum" ]
    }
   ]
  }
 ]
}