{
 "title": "AWS CloudFront",
 "description": "Visualize AWS CloudFront metrics",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   {
    "name": "distributionid",
    "label": "DistributionId",
    "query": "dimension_values(us-east-1, AWS/CloudFront, Requests, DistributionId)"
   }
  ]
 },
 "panels": [
  {
   "title": "Requests / TotalErrorRate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DistributionId": "$distributionid", "Region": "Global" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "Requests",
     "namespace": "AWS/CloudFront",
     "options": {
      "showDisabledItems": false
     },
     "region": "us-east-1",
     "statistics": [ "Sum" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "DistributionId": "$distributionid", "Region": "Global" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "TotalErrorRate",
     "namespace": "AWS/CloudFront",
     "options": {
      "showDisabledItems": false
     },
     "region": "us-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "4xxErrorRate / 5xxErrorRate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DistributionId": "$distributionid", "Region": "Global" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "4xxErrorRate",
     "namespace": "AWS/CloudFront",
     "options": {
      "showDisabledItems": false
     },
     "region": "us-east-1",
     "statistics": [ "Average" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "DistributionId": "$distributionid", "Region": "Global" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "5xxErrorRate",
     "namespace": "AWS/CloudFront",
     "options": {
      "showDisabledItems": false
     },
     "region": "us-east-1",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "BytesDownloaded / BytesUploaded",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DistributionId": "$distributionid", "Region": "Global" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "BytesDownloaded",
     "namespace": "AWS/CloudFront",
     "options": {
      "showDisabledItems": false
     },
     "region": "us-east-1",
     "statistics": [ "Sum" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "DistributionId": "$distributionid", "Region": "Global" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "BytesUploaded",
     "namespace": "AWS/CloudFront",
     "options": {
      "showDisabledItems": false
     },
     "region": "us-east-1",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "DistributionId": "$distributionid", "Region": "Global" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "Requests",
     "namespace": "AWS/CloudFront",
     "options": {
      "showDisabledItems": false
     },
     "region": "us-east-1",
     "statistics": [ "Sum" ]
    }
   ]
  }
 ]
}