{
 "title": "DynamoDB",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Datasource", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   { "name": "DB", "label": "DB", "query": "namespaces()" },
   {
    "name": "Tablename",
    "label": "TableName",
    "query": "dimension_values($region, $DB, , TableName)"
   }
  ]
 },
 "panels": [
  {
   "title": "Write Consumption",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "dimensions": { "TableName": "$Tablename" },
     "metricName": "ProvisionedWriteCapacityUnits",
     "namespace": "$DB",
     "period": "300",
     "region": "$region",
     "statistics": [ "Maximum" ]
    },
    {
     "alias": "ConsumedWriteCapacity/min",
     "expression": "a/300",
     "id": "c",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Read Consumption",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 10 },
   "targets": [
    {
     "dimensions": { "TableName": "$Tablename" },
     "metricName": "ProvisionedReadCapacityUnits",
     "namespace": "$DB",
     "period": "300",
     "region": "$region",
     "statistics": [ "Maximum" ]
    },
    {
     "alias": "ConsumedReadCapacity/min",
     "expression": "a/300",
     "id": "c",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Throttle Events",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 20 },
   "targets": [
    {
     "dimensions": { "TableName": "$Tablename" },
     "id": "a",
     "metricName": "ReadThrottleEvents",
     "namespace": "$DB",
     "period": "300",
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "dimensions": { "TableName": "$Tablename" },
     "metricName": "WriteThrottleEvents",
     "namespace": "$DB",
     "period": "300",
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "dimensions": { "TableName": "$Tablename" },
     "metricName": "ThrottledRequests",
     "namespace": "$DB",
     "period": "300",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  }
 ]
}