{
 "title": "Amazon EC2",
 "description": "Visualize Amazon EC2 metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data source", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   { "name": "period", "label": "Period [sec]", "query": "60,300,3600" },
   {
    "name": "Tags",
    "label": "Tags",
    "query": "ec2_instance_attribute($region, Tags.Name, {})"
   },
   {
    "name": "InstaceID",
    "label": "InstanceID",
    "query": "ec2_instance_attribute($region, InstanceId, {\"tag:Name\": [\"$Tags\"]})"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU utilization per instance [max %]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "{{InstanceId}}",
     "dimensions": { "InstanceId": "$InstaceID" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/EC2",
     "period": "$period",
     "region": "$region",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "Total network traffic outbound (+) and inbound (-) [bytes/sec]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Inbound",
     "dimensions": { "InstanceId": "*" },
     "expression": "SUM(REMOVE_EMPTY(SEARCH('{AWS/EC2,InstanceId} MetricName=\"NetworkIn\"', 'Sum', $period)))/$period",
     "metricName": "NetworkOut",
     "namespace": "AWS/EC2",
     "period": "$period",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "Outbound",
     "dimensions": { "InstanceId": "*" },
     "expression": "SUM(REMOVE_EMPTY(SEARCH('{AWS/EC2,InstanceId} MetricName=\"NetworkOut\"', 'Sum', $period)))/$period",
     "metricName": "NetworkOut",
     "namespace": "AWS/EC2",
     "period": "$period",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "InstanceId": "$InstaceID" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "NetworkIn",
     "namespace": "AWS/EC2",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "InstanceId": "$InstaceID" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "NetworkOut",
     "namespace": "AWS/EC2",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "NetworkPackets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "InstanceId": "$InstaceID" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "NetworkPacketsIn",
     "namespace": "AWS/EC2",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "InstanceId": "$InstaceID" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "NetworkPacketsOut",
     "namespace": "AWS/EC2",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Status Checks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status check failed [Sum]",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "InstanceId": "$InstaceID" },
       "metricName": "StatusCheckFailed",
       "namespace": "AWS/EC2",
       "period": "$period",
       "region": "$region",
       "statistics": [ "Sum" ]
      }
     ]
    },
    {
     "title": "Instance status check failed [Sum]",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "InstanceId": "$InstaceID" },
       "metricName": "StatusCheckFailed",
       "namespace": "AWS/EC2",
       "period": "$period",
       "region": "$region",
       "statistics": [ "Sum" ]
      }
     ]
    },
    {
     "title": "System status check failed [Sum]",
     "type": "graph",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 45 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "dimensions": { "InstanceId": "$InstaceID" },
       "metricName": "StatusCheckFailed",
       "namespace": "AWS/EC2",
       "period": "$period",
       "region": "$region",
       "statistics": [ "Sum" ]
      }
     ]
    }
   ]
  }
 ]
}