{
 "title": "Amazon RDS OS Metrics",
 "description": "Visualize OS metrics for Amazon RDS instance",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Datasource", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "instance",
    "label": "DB Instance",
    "query": "dimension_values($region,AWS/RDS,CPUUtilization,DBInstanceIdentifier)"
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPU",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "period": "60",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "CPU Credit Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Credits Accumulated",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "metricName": "CPUCreditBalance",
     "namespace": "AWS/RDS",
     "period": "300",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "Credits Consumed",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "metricName": "CPUCreditUsage",
     "namespace": "AWS/RDS",
     "period": "300",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Disk Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "Read",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "metricName": "ReadIOPS",
     "namespace": "AWS/RDS",
     "period": "60",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "Write",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "metricName": "WriteIOPS",
     "namespace": "AWS/RDS",
     "period": "60",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Read",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "metricName": "ReadThroughput",
     "namespace": "AWS/RDS",
     "period": "60",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "Write",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "metricName": "WriteThroughput",
     "namespace": "AWS/RDS",
     "period": "60",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Disk Queue Depth",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Outstanding IO Requests",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "metricName": "DiskQueueDepth",
     "namespace": "AWS/RDS",
     "period": "60",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Storage Space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Available",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/RDS",
     "period": "60",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Available",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "period": "60",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Inbound",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "metricName": "NetworkReceiveThroughput",
     "namespace": "AWS/RDS",
     "period": "60",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "Outbound",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "metricName": "NetworkTransmitThroughput",
     "namespace": "AWS/RDS",
     "period": "60",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Replicalag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Used",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "metricName": "ReplicaLag",
     "namespace": "AWS/RDS",
     "period": "60",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "DataBaseConnections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Used",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "period": "60",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  }
 ]
}