{
 "title": "Node Exporter (Windows)",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Cloud",
    "label": "Cloud",
    "query": {
     "query": "label_values(windows_cpu_time_total{job=\"node_exporter_metrics\"},cloud)"
    }
   },
   {
    "name": "Server",
    "label": "Server",
    "query": {
     "query": "label_values(windows_cpu_time_total{cloud=\"$Cloud\"},name)"
    }
   },
   {
    "name": "IP",
    "label": "IP",
    "query": {
     "query": "label_values(windows_cpu_time_total{name=\"$Server\"},instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Available Disk Space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "windows_logical_disk_free_bytes{instance=\"$IP\"} ",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Used CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": " 100 - (avg by(instance) (irate(windows_cpu_time_total{mode=\"idle\", instance=\"$IP\"}[10m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(windows_os_virtual_memory_free_bytes{instance=\"$IP\"} / windows_os_virtual_memory_bytes {instance=\"$IP\"}) *100",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}