modules:
  http_2xx:
    prober: http
    timeout: 5s
    http:      
      valid_status_codes: []  # Defaults to 2xx
      method: GET            
      headers:
        User-Agent: "blackbox-monitoring"
      fail_if_ssl: false
      fail_if_not_ssl: false      
      tls_config:
        insecure_skip_verify: true
      preferred_ip_protocol: "ip4" # defaults to "ip6"
