{
 "title": "Firebase Database",
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Datasource", "query": "stackdriver" },
   {
    "name": "Project",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Downloads",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "firebasedatabase.googleapis.com/network/monthly_sent",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$Project",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Storage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "firebasedatabase.googleapis.com/storage/total_bytes",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$Project",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "Connections",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "firebasedatabase.googleapis.com/network/active_connections",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$Project",
      "query": "",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "DataBase Load",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [],
      "groupBys": [ "metric.label.type" ],
      "metricKind": "GAUGE",
      "metricType": "firebasedatabase.googleapis.com/io/database_load",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$Project",
      "query": "",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Download Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "firebasedatabase.googleapis.com/network/monthly_sent",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$Project",
      "query": "",
      "valueType": "INT64"
     },
     "sloQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "simplilearnrd",
      "selectorName": "select_slo_health",
      "serviceId": "",
      "serviceName": "",
      "sloId": "",
      "sloName": ""
     }
    }
   ]
  },
  {
   "title": "Response count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "firebasedatabase.googleapis.com/io/sent_responses_count",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "rate",
      "projectName": "$Project",
      "query": "",
      "valueType": "INT64"
     },
     "sloQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "simplilearnrd",
      "selectorName": "select_slo_health",
      "serviceId": "",
      "serviceName": "",
      "sloId": "",
      "sloName": ""
     }
    }
   ]
  },
  {
   "title": "Connections",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 36 },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "firebasedatabase.googleapis.com/network/active_connections",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$Project",
      "query": "",
      "valueType": "INT64"
     },
     "sloQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "simplilearnrd",
      "selectorName": "select_slo_health",
      "serviceId": "",
      "serviceName": "",
      "sloId": "",
      "sloName": ""
     }
    }
   ]
  },
  {
   "title": "Total Billed Bytes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "editorMode": "visual",
      "filters": [],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "firebasedatabase.googleapis.com/network/sent_bytes_count",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "rate",
      "projectName": "$Project",
      "query": "",
      "valueType": "INT64"
     },
     "sloQuery": {
      "aliasBy": "",
      "alignmentPeriod": "cloud-monitoring-auto",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "simplilearnrd",
      "selectorName": "select_slo_health",
      "serviceId": "",
      "serviceName": "",
      "sloId": "",
      "sloName": ""
     }
    }
   ]
  }
 ]
}